name: Python application

on:
  push:
    branches: [ "main" ]
    paths: [ '**/*.py' ]
  pull_request:
    branches: [ "main" ]
    paths: [ '**/*.py' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      -
        name: Check out code
        uses: actions/checkout@v4

      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      -
        name: Get list of changed files
        id: changed
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD -- '*.py' > changed.txt

      -
        name: Analyze affected dependencies
        run: |
          python .github/scripts/scripts_analyze_dependencies.py changed.txt

      -
        name: Lint affected non-test files with pylint
        run: |
          if [ -s affected_files.txt ]; then
            echo "Linting affected files:"
            cat affected_files.txt
            xargs pylint < affected_files.txt --exit-zero
          else
            echo "No affected non-test files to lint."
          fi

      -
        name: Run affected tests with unittest
        run: |
          if [ -s affected_tests.txt ]; then
            echo "Running affected test files:"
            cat affected_tests.txt
            xargs -n 1 python -m unittest
          else
            echo "No affected test files to run."
          fi
